import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StarsCanvas from './Components/StarBackground'
import NavBar from './Components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
      className={`${inter.className} bg-[#030014] overflow-y-scroll overflow-x-hidden`}>
          <NavBar />
          <StarsCanvas />
          {children}
      </body>
    </html>
  )
}
